version: "3.0"
services:
  app:
    build: .
    volumes:
      - ./darts:/darts
    working_dir: /darts
    entrypoint: python /darts/docker_entrypoint.py
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      - PYTHONUNBUFFERED=yup
      - DATABASE_URL=postgres://darts_user:darts_password@db/darts
      - RUNNING_IN_DOCKER=yup
      - DJANGO_SETTINGS_MODULE=darts.settings.dev
      - ALLOWED_HOSTS=localhost,app,0.0.0.0
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15.7
    environment:
      - POSTGRES_DB=darts
      - POSTGRES_USER=darts_user
      - POSTGRES_PASSWORD=darts_password
    volumes:
      - ./data/db15:/var/lib/postgresql/data

  owasp:
    image: owasp/zap2docker-weekly
    command: zap-baseline.py -t http://app:8000 -c zap.conf -I -r zap_report.html
    depends_on:
      - app
    volumes:
      - .:/zap/wrk/
    profiles: ["owasp-scan"]


  # gulp image goes here
