# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/python:3.10-browsers
        environment:
          - PIPENV_VENV_IN_PROJECT=true
          - DJANGO_SETTINGS_MODULE=darts.settings.prod
          - DATABASE_URL=postgres://darts_user:darts_password@localhost/darts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: cimg/postgres:14.2
        environment:
          - POSTGRES_DB=darts
          - POSTGRES_USER=darts_user
          - POSTGRES_PASSWORD=darts_password

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install --dev --deploy
            npm ci
            npx gulp init
            npx gulp compile

      - save_cache:
          paths:
            - ./.venv
            - ~/.npm
          key: deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}

      # run tests!
      - run:
          name: run tests
          command: |
            cd darts
            pipenv run python manage.py test --noinput
            pipenv run flake8
            pipenv run black --check --diff .
            
      # pipenv run bandit -r . -x docker_entrypoint.py

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  # deploy to staging here

  # deploy to production here

workflows:
  version: 2
  build_pull_requests:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
