# Generated by Django 5.1 on 2024-12-18 02:54

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.BinaryField()),
                ('body', models.TextField()),
                ('search_text', django.contrib.postgres.search.SearchVectorField()),
            ],
        ),

        # It appears to be impossible to alter an existing column to be generated, so
        # we drop the column and re-create it here.
        migrations.RunSQL(
            sql="""
                ALTER TABLE search_document DROP COLUMN search_text;

                ALTER TABLE search_document
                ADD COLUMN search_text tsvector
                GENERATED ALWAYS AS
                    (to_tsvector('english', coalesce(filename, '') || ' ' || coalesce(body, '')))
                STORED;
                """,

            # SQL that does nothing, so that Django knows we can reverse the migration
            reverse_sql="SELECT 'reversing' as message"
        ),
    ]
