# Generated by Django 5.1 on 2025-01-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
