# Generated by Django 5.1 on 2025-01-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_case_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.region'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.case'),
        ),
    ]
