# Generated by Django 5.1 on 2025-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cases',
            field=models.ManyToManyField(blank=True, to='search.case'),
        ),
    ]
