# Generated by Django 5.1 on 2025-01-27 17:20

from django.db import migrations, models
from django.template.defaultfilters import slugify

def add_slugs(apps, schema_editor):
    Document = apps.get_model("search", "Document")
    for document in Document.objects.all():
        document.slug = slugify(document.title)
        document.save(update_fields=["slug"])


def reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_person_first_name_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.RunPython(add_slugs, reverse),
    ]
