# Generated by Django 5.1 on 2025-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_case_affected_doi_resources_case_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
