# Generated by Django 5.1 on 2025-01-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='document',
            name='filename_normal',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),

        migrations.RunSQL(
            sql="""
                ALTER TABLE search_document DROP COLUMN search_text;

                ALTER TABLE search_document
                ADD COLUMN search_text tsvector
                GENERATED ALWAYS AS
                    (to_tsvector('english',
                        coalesce(title, '') || ' ' ||
                        coalesce(filename, '') || ' ' ||
                        coalesce(filename_normal, '') || ' ' ||
                        coalesce(body, '')
                    ))
                STORED;
                """,

            # SQL that does nothing, so that Django knows we can reverse the migration
            reverse_sql="SELECT 'reversing' as message"
        ),
    ]
