name: Python and Javascript dependency scans

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at noon UTC each Monday (7am EST / 8am EDT)
    - cron: '0 12 * * 1'

jobs:
  pipenv-check:
    name: Pipenv dependency security check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-languages

      - name: Update advisory database and run checks
        run: pipenv check

  
  npm-audit:
    name: Npm audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-languages

      - name: Run npm audit
        run: npm audit
  